### ISSUE TITLE
The margin and  distance type in your implementation

### ISSUE THREAD

**Issue by 1170300714** [JosephKJ/OWOD#34]
Thanks for your greate job!
I found that the hyper-parameter 'margin' and the 'distance type'  in your code is the opposite of your paper report：
In your code:(detectron2/modeling/roi_heads/fast_rcnn.py/FastRCNNOutputLayers)
`self.hingeloss = nn.HingeEmbeddingLoss(2)` means the margin is 2.

`distances = torch.cdist(fg_features, torch.stack(all_means).cuda(), p=self.margin)` where in your code the p(self.margin) is 10, which means a 10-Norm

But in your papar:
![image](https://user-images.githubusercontent.com/40813341/115509544-26468900-a2b1-11eb-9670-3af61f3100e5.png)
You said that the distance is  Euclidean distance so the p is should be 2 and the margin should be 10.

I suspect you are writing the reverse
Looking forward to your apply.

**Comment by JosephKJ** [comment]
Hi @1170300714 : thanks for catching this. I will update.

**Comment by dyabel** [comment]
> Hi @1170300714 : thanks for catching this. I will update.

The latest code still not correct this error. Does your reproduce results use the previous version? Looking forward to your replay.

**Comment by JosephKJ** [comment]
Its a writing and variable name issue. It will not affect the results.

**Comment by qianyizhang** [comment]
> Its a writing and variable name issue. It will not affect the results.

NO, its NOT a naming error, and you should seriously fix this and perhaps rerun the experiments.

Though I believe this does not affect most conclusion+novelty of this paper, it defintely discredit supplementary section C.
since by increasing distance you making the UNK more selective, and by increasing p-Norm (as in the code), you simply shifting towards evaluation the largest value in feature vector, which I think is largely irrelevant.

**Comment by LinyeLi60** [comment]
这代码真的是无语了，我真怀疑他论文里的实验数据都是错的，虽然我这样评价很不礼貌，但是作者对于学术的严谨性令人怀疑！代码明明写错了，偏说是命名错误。

**Comment by 1170300714** [comment]
收到，感谢您的来件
